### ISSUE TITLE
Make available a -f/--full flag for the CLI mode

### ISSUE THREAD

**Issue by tanuj101** [tanuj101/instagram-api#9]
This command should get show all the data that the API fetches in tabular or some other way just like it works with -m/--meta flag.
example-
`instaget -f selenagomez`

**Comment by shawnlobo96** [comment]
@tanuj101 Is this still open for contribution?

Does this work?

![image](https://user-images.githubusercontent.com/9108506/95689094-2ee84380-0c2c-11eb-94fd-b5594a3d747f.png)

**Comment by tanuj101** [comment]
Nice this looks good @shawnlobo96
